### ISSUE TITLE
怎么用vs2015打不开呢

### ISSUE THREAD

**Issue by kinggod** [shenniubuxing3/PressureTool#1]
如题，打开PressureTool.csproj之后，没有任何东西呢？bin里面也没有执行的 ，希望作者能给说明下 
thanks

**Comment by shenniubuxing3** [comment]
项目用的是netcore1.1版本，如果您还是1。1一下版本是打不开的，因为1.1以前都是json配置文件来加载项目的，而1.1及以后的版本升级为。csproj来加载项目（也就是xml格式），可以参考下这里：https://docs.microsoft.com/zh-cn/dotnet/core/tools/project-json-to-csproj； 

bin里面没有运行文件，需要您是为了上传到git包更小，需要自己动手dotnet run或者dotnet publish 发布生成运行文件，可以参考这：http://www.cnblogs.com/wangrudong003/p/6591104.html

**Comment by kinggod** [comment]
已经解决，把.cs 和。json的放到自己新建的一个项目里面引用相关文件调整下就可以了 ，
